### ISSUE TITLE
Missing cmf_uid?

### ISSUE THREAD

**Issue by dholth** [collective/collective.catalogcleanup#2] opened 2015-04-29 13:18 UTC
I somehow wound up with a Plone site that was missing the unique id cmf_uid on many Documents, which are apparently distinct from the unique id UID which are apparently distinct from the unique id UUID. It wouldn't appear to matter except that it prevents plone.app.iterate from being able to check in working copies. collective.catalogcleanup did not fix the problem.

Would a script like the following be a useful addition to collective.catalogcleanup? http://stackoverflow.com/questions/29926745/in-plone-how-do-i-fix-archetypes-content-that-is-missing-the-cmf-uid-annotati/29944932#29944932

**Comment by mauritsvanrees** [comment] 2015-04-29 16:50
I don't know if that is a good idea.  cmf_uid comes from Products.CMFEditions (and Products.CMFUid). At least CMFEditions adds a cmf_uid index in the portal_catalog because it needs it.  I see no reference to cmf_uid or those packages in plone.app.iterate, except for an import of permissions from CMFEdition.  So it would surprise me if this is related.

You may be right, but I am hesitant to include something that I do not understand.

Do you maybe have a scenario with some steps to follow to reproduce the problem?

**Comment by mauritsvanrees** [comment] 2015-04-29 17:12
I have a client site where I have only 24 distinct cmf_uid entries in the portal_catalog index. So apparently it need not be unique. Most of the content is custom content types though, and maybe they do not inherit from the right base classes to get a cmf_uid. I do not have Iterate installed there.

I have now installed Iterate in a local copy of that site. Iterate does not work for my custom content types, but that is probably normal. When I try it on standard pages, it works just fine. Most pages seem to have cmf_uids that are actually unique. But when I create a checkout, the new working copy gets the same cmf_uid. Normal copies also get the same cmf_uid. So I don't think the cmf_uid really needs to be totally unique. I have not tried your script, but that may create different cmf_uids for (working) copies and you may not want that.

So: at the moment this script seems unneeded to me as addition for collective.catalogcleanup.

I'll close this ticket. But if you have more information or want to discuss further, feel free to reopen it.

**Closed by mauritsvanrees** 2015-04-29 17:12 UTC

**Comment by dholth** [comment] 2015-04-30 02:21
The script fixed my problem, I don't know how I got the problem, maybe
too much importing between sites. Thank you for looking, maybe I only
needed to add cmf_uid to working copies and their originals.

A better fix might be to make iterate tolerant of a missing cmf_uid.

On Wed, Apr 29, 2015, at 12:50 PM, Maurits van Rees wrote:
> I don't know if that is a good idea. cmf_uid comes from
> Products.CMFEditions (and Products.CMFUid). At least CMFEditions adds
> a cmf_uid index in the portal_catalog because it needs it. I see no
> reference to cmf_uid or those packages in plone.app.iterate, except
> for an import of permissions from CMFEdition. So it would surprise me
> if this is related.


> You may be right, but I am hesitant to include something that I do not
> understand.


> Do you maybe have a scenario with some steps to follow to reproduce
> the problem?


> — Reply to this email directly or view it on GitHub[1].

>



Links:

  1. https://github.com/collective/collective.catalogcleanup/issues/2#issuecomment-97501834
